/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project;

/**
 *
 * @author Ahmed Ehabb
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_gallery = new javax.swing.JButton();
        btn_subscrebtions = new javax.swing.JButton();
        btn_exercise = new javax.swing.JButton();
        btn_healthyFood = new javax.swing.JButton();
        btn_calories = new javax.swing.JButton();
        btn_logOut = new javax.swing.JButton();
        btn_DeleteAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_gallery.setBackground(new java.awt.Color(0, 0, 0));
        btn_gallery.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_gallery.setForeground(new java.awt.Color(19, 209, 226));
        btn_gallery.setText("Gallery");
        btn_gallery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 209, 226), 2));
        getContentPane().add(btn_gallery, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 190, 60));

        btn_subscrebtions.setBackground(new java.awt.Color(0, 0, 0));
        btn_subscrebtions.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_subscrebtions.setForeground(new java.awt.Color(19, 209, 226));
        btn_subscrebtions.setText("Subscriptions");
        btn_subscrebtions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 209, 226), 2, true));
        btn_subscrebtions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subscrebtionsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_subscrebtions, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 190, 60));

        btn_exercise.setBackground(new java.awt.Color(0, 0, 0));
        btn_exercise.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_exercise.setForeground(new java.awt.Color(19, 209, 226));
        btn_exercise.setText("Exercise");
        btn_exercise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 209, 226), 2));
        btn_exercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exerciseActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 190, 60));

        btn_healthyFood.setBackground(new java.awt.Color(0, 0, 0));
        btn_healthyFood.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_healthyFood.setForeground(new java.awt.Color(19, 209, 226));
        btn_healthyFood.setText("Healthy Food");
        btn_healthyFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 209, 226), 2));
        getContentPane().add(btn_healthyFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 190, 60));

        btn_calories.setBackground(new java.awt.Color(0, 0, 0));
        btn_calories.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_calories.setForeground(new java.awt.Color(19, 209, 226));
        btn_calories.setText("Calories calc");
        btn_calories.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 209, 226), 2));
        getContentPane().add(btn_calories, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 190, 60));

        btn_logOut.setBackground(new java.awt.Color(0, 0, 0));
        btn_logOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\ehaba\\Downloads\\turn-off.png")); // NOI18N
        btn_logOut.setBorder(null);
        getContentPane().add(btn_logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 100, 50));

        btn_DeleteAccount.setBackground(new java.awt.Color(0, 0, 0));
        btn_DeleteAccount.setIcon(new javax.swing.ImageIcon("C:\\Users\\ehaba\\Downloads\\delete.png")); // NOI18N
        btn_DeleteAccount.setBorder(null);
        getContentPane().add(btn_DeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ehaba\\Downloads\\anastase-maragos-9dzWZQWZMdE-unsplash.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_subscrebtionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subscrebtionsActionPerformed
        // TODO add your handling code here:
        this.dispose();
         new Subscriptions().setVisible(true);
    }//GEN-LAST:event_btn_subscrebtionsActionPerformed

    private void btn_exerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exerciseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exerciseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteAccount;
    private javax.swing.JButton btn_calories;
    private javax.swing.JButton btn_exercise;
    private javax.swing.JButton btn_gallery;
    private javax.swing.JButton btn_healthyFood;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JButton btn_subscrebtions;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
